version: '3'
services:
  postgres:
    container_name: postgres
    image: mdillon/postgis
    environment:
      POSTGRES_MULTIPLE_DATABASES: user_data,gov_auth
      POSTGRES_USER: commhawk
      POSTGRES_PASSWORD: password
    volumes:
        - postgres:/data/postgres
        - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: unless-stopped

  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:latest
    ports:
      - "3004:8080"
      - "29015:29015"
      - "28015:28015"
    volumes: 
      - rethinkdb:/data

  user_data_service:
    build: './user_data_service'
    container_name: uds
    ports: 
      - "3002:3000"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://commhawk:password@postgres:5432/user_data
    volumes: 
      - ./user_data_service:/src
      # - container_node_modules:/src/node_modules
  
  gov_authority_service:
    build: './gov_authority_service'
    container_name: gov_auth
    ports:
      - "3001:3000"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://commhawk:password@postgres:5432/gov_auth
    volumes:
      - ./gov_authority_service:/src 



  socket_service:
    build: './socket_service'
    container_name: socket
    ports: 
      - "3003:3000"
    volumes: 
      - ./socket_service:/src


  api_gateway:
    image: express-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - user_data_service
      - socket_service
    volumes: 
      - ./api_gateway/gateway.config.yml:/var/lib/eg/gateway.config.yml 
    

volumes:
  postgres:
  rethinkdb:
  # container_node_modules:

 
