version: '3'
services:
  postgres:
    container_name: postgres
    image: mdillon/postgis
    environment:
      POSTGRES_MULTIPLE_DATABASES: user_data,gov_auth
      POSTGRES_USER: commhawk
      POSTGRES_PASSWORD: password
    volumes:
        - postgres:/data/postgres
        - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: unless-stopped

  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:latest
    ports:
      - "3004:8080"
      - "29015:29015"
      - "28015:28015"
    volumes: 
      - rethinkdb:/data

  user_data_service:
    build: './user_data_service'
    container_name: uds
    ports: 
      - "3002:3000"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://commhawk:password@postgres:5432/user_data
    volumes: 
      - ./user_data_service:/src
      # - container_node_modules:/src/node_modules
  
  gov_authority_service:
    build: './gov_authority_service'
    container_name: gov_auth
    ports:
      - "3001:3000"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://commhawk:password@postgres:5432/gov_auth
    volumes:
      - ./gov_authority_service:/src
      
  push_notification_service:
    build: './push_notification_service'
    container_name: push
    ports:
      - "3005:3000"
    depends_on: 
      - user_data_service
      - gov_authority_service
    volumes: 
      - ./push_notification_service:/src  

  socket_service:
    build: './socket_service'
    container_name: socket
    ports: 
      - "3003:3000"
    depends_on: 
      - rethinkdb
    environment: 
      DATABASE_URL: postgres://commhawk:password@postgres:5432/gov_auth
      SECRET_ACESS_KEY: LnGXC4KhIgs0qed+fABje1xfcyFDCyil7e9Wgprw
      ACCESS_KEY: ASIATPIHHDYUKHZI4Z4O
      SESSION_TOKEN: FwoGZXIvYXdzEJT//////////wEaDKt9/FFrjvA6AuboPiLNAR6UKqFgUXV1WJAVDcj2RzOf6JhToSBI1hLF+shbz4cEtwRiyMix9Zo1lNjhKUBHYkIN5Dw8M/fzhOxJSH5hQeJ3YahKwSTG6cZEo4pz0oOKLQDNYczBPDxOWJKJzvqRcXgGg3oF3fkab64KkgjNIfPuVXe2dEztYzY2xR3kQAI1EulgRYiVUEVa3RwGxl62eHben3yjWskp422ybketcwEAuGjTe5t3vAUR5DX0cGHcXtsbGUjusNiFv+B35xvwzbwRpmJgU4PXuErgCA0ow7X49gUyLW0+AJs+14upCb+ZhBig3FnOkzyeACEyf/Ys/qkt04kOwF6fXzr+DiKSxbxYKg==
    volumes: 
      - ./socket_service:/src


  api_gateway:
    image: express-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - user_data_service
      - socket_service
    volumes: 
      - ./api_gateway/gateway.config.yml:/var/lib/eg/gateway.config.yml 
    

volumes:
  postgres:
  rethinkdb:
  # container_node_modules:

 
