version: '3'
services:
  postgres:
    container_name: postgres
    image: mdillon/postgis
    environment:
      POSTGRES_MULTIPLE_DATABASES: user_data,gov_auth
      POSTGRES_USER: commhawk
      POSTGRES_PASSWORD: password
    volumes:
        - postgres:/data/postgres
        - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: unless-stopped

  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:latest
    ports:
      - "3004:8080"
      - "29015:29015"
      - "28015:28015"
    volumes: 
      - rethinkdb:/data

  user_data_service:
    build: './user_data_service'
    container_name: uds
    ports: 
      - "3002:3000"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://commhawk:password@postgres:5432/user_data
    volumes: 
      - ./user_data_service:/src
      # - container_node_modules:/src/node_modules
  
  gov_authority_service:
    build: './gov_authority_service'
    container_name: gov_auth
    ports:
      - "3001:3000"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://commhawk:password@postgres:5432/gov_auth
    volumes:
      - ./gov_authority_service:/src
      
  push_notification_service:
    build: './push_notification_service'
    container_name: push
    ports:
      - "3005:3000"
    depends_on: 
      - user_data_service
      - gov_authority_service
    volumes: 
      - ./push_notification_service:/src  

  socket_service:
    build: './socket_service'
    container_name: socket
    ports: 
      - "3003:3000"
    depends_on: 
      - rethinkdb
    environment: 
      DATABASE_URL: postgres://commhawk:password@postgres:5432/gov_auth
      SECRET_ACCESS_KEY: JqFuuSqodm4OOMu9Tl9pQ9UP2y6/RPMQkyCnWGhn
      ACCESS_KEY: ASIATPIHHDYUA7ZT7E53
      SESSION_TOKEN: FwoGZXIvYXdzEKj//////////wEaDBrxkn3tlVxMXTb8KiLNAUxPIPxtY6jG0eciz2KQSip69EjXUGKPepeMHEOum2RkHQy3LYb0AyILXrA9HxnCWGSNBUy8VFC2D/HZZ8lOM+zHR7Y6hJ47ULTUQRlAXWg1qg/z/xn52PK0QTCrx0M0miNMudQ4Wbiit1LOSrXmDpHJ7JqmanNUlSc+hes64h6Hhiu3gR/2L0X04k8mlQPXr+D9kpUQJQ19fIaysFybcIcfUqBbs3k6QwFf9a2suRGGNEzYhdjgbAIgAgwahPzaTpmDKlr+od5CMgBoApso3OD89gUyLWjVilUKZEQpzYxywwTAa/cHfPe/ce0p1xuLQQBfy3jkSMMLcwnsm1Y3L80yPQ==
    volumes: 
      - ./socket_service:/src


  api_gateway:
    image: express-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - user_data_service
      - socket_service
    volumes: 
      - ./api_gateway/gateway.config.yml:/var/lib/eg/gateway.config.yml 
    

volumes:
  postgres:
  rethinkdb:
  # container_node_modules:

 
