http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  noAuth:
    host: '*'
    paths: 
      - '/api/user/signup'
      - '/api/user/signin'
    methods: ["POST"]
  user:
    host: '*'
    paths:
      - '/api/user/update'
      - '/api/user/delete'
      - '/api/user/:userId'
    methods: ["GET","POST","PUT","DELETE"]
  socket:
    host: '*'
    paths:
      - '/api/socket/broadcast'
      - '/api/socket/test' 
serviceEndpoints:
  noAuthService:
    url: 'http://uds:3000'
  socketService:
    url: 'htpp://socket:3000'
policies:
  - log
  - proxy
  - jwt
  - request-transformer
pipelines:
  noAuth:
    apiEndpoints:
      - noAuth
    policies:
      - proxy:
        - action:
            serviceEndpoint: noAuthService
  
  user:
    apiEndpoints:
      - user
    policies:
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false      
      
      - request-transformer:
        - action:
            body:
              add:
                user: req.user
      - proxy:
        - action:
            serviceEndpoint: noAuthService

  socket:
    apiEndpoints:
      - socket
    policies:
      - proxy:
        - action:
            serviceEndpoint: socketService
      