http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  noAuth:
    host: '*'
    paths: 
      - '/api/user/signup'
      - '/api/user/signin'
    methods: ["POST"]
  user:
    host: '*'
    paths:
      - '/api/user/update'
      - '/api/user/delete'
      - '/api/user/:userId'
    methods: ["GET","POST","PUT","DELETE"]
  gov_no_auth:
    host: '*'
    paths:
      - '/api/gov/signup'
      - '/api/gov/signin'
      - '/api/gov/get-all'
  gov_auth:
    host: '*'
    paths:
      - '/api/gov/get-institute-info'
  socket:
    host: '*'
    paths:
      - '/api/socket/broadcast'
      - '/api/socket/test'
      - '/api/socket/send-message' 
serviceEndpoints:
  noAuthService:
    url: 'http://uds:3000'
  socketService:
    url: 'htpp://socket:3000'
  govNoAuthService:
    url: 'http://gov_auth:3000'
  govAuthService:
    url: 'http://gov_auth:3000'
policies:
  - log
  - proxy
  - jwt
  - request-transformer
  - terminate
  - cors
pipelines:
  noAuth:
    apiEndpoints:
      - noAuth
    policies:
      - proxy:
        - action:
            serviceEndpoint: noAuthService
  
  user:
    apiEndpoints:
      - user
    policies:
      - cors:
        - action:
            origin: '*'
            credentials: true
            methods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept']
            exposedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept']
            #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
            optionsSuccessStatus: 204
            #maxAge: 600
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false
      - request-transformer:
        - action:
            body:
              add:
                token: req.user
      - proxy:
        - action:
            serviceEndpoint: noAuthService

  socket:
    apiEndpoints:
      - socket
    policies:
      - cors:
        - action:
            origin: '*'
            credentials: true
            methods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept']
            exposedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept']
            #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
            optionsSuccessStatus: 204
            #maxAge: 600
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false
      - request-transformer:
        - action:
            body:
              add:
                token: req.user
      - proxy:
        - action:
            serviceEndpoint: socketService
  
  gov_auth:
    apiEndpoints:
      - gov_auth
    policies:
      - cors:
        - action:
            origin: '*'
            credentials: true
            methods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept']
            exposedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept']
            #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
            optionsSuccessStatus: 204
            #maxAge: 600
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false
      - request-transformer:
        - action:
            body:
              add:
                token: req.user
      - proxy:
        - action:
            serviceEndpoint: govAuthService
  
  gov_no_auth:
    apiEndpoints:
      - gov_no_auth
    policies:
      - cors:
        - action:
            origin: '*'
            credentials: true
            methods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept']
            exposedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept']
            #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
            optionsSuccessStatus: 204
            #maxAge: 600
      - proxy:
        - action:
            serviceEndpoint: govNoAuthService

      