http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  noAuth:
    host: '*'
    paths: 
      - '/api/user/signup'
      - '/api/user/signin'
    methods: ["POST"]
  user:
    host: '*'
    paths:
      - '/api/user/update'
      - '/api/user/delete'
      - '/api/user/:userId'
    methods: ["GET","POST","PUT","DELETE"]
  gov_no_auth:
    host: '*'
    paths:
      - '/api/gov/signup'
      - '/api/gov/signin'
  gov_auth:
    host: '*'
    paths:
      - '/api/gov/get-all'
      - '/api/gov/get-institute-info'
  socket:
    host: '*'
    paths:
      - '/api/socket/broadcast'
      - '/api/socket/test'
      - '/api/socket/send-message' 
serviceEndpoints:
  noAuthService:
    url: 'http://uds:3000'
  socketService:
    url: 'htpp://socket:3000'
  govNoAuthService:
    url: 'http://gov_auth:3000'
  govAuthService:
    url: 'http://gov_auth:3000'
policies:
  - log
  - proxy
  - jwt
  - request-transformer
  - terminate
pipelines:
  noAuth:
    apiEndpoints:
      - noAuth
    policies:
      - proxy:
        - action:
            serviceEndpoint: noAuthService
  
  user:
    apiEndpoints:
      - user
    policies:
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false
            passThrough: true  
      
      - request-transformer:
        - action:
            body:
              add:
                user: req.user
      - proxy:
        - action:
            serviceEndpoint: noAuthService

  socket:
    apiEndpoints:
      - socket
    policies:
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false
      - request-transformer:
        - action:
            body:
              add:
                token: req.user
      - proxy:
        - action:
            serviceEndpoint: socketService
  
  gov_auth:
    apiEndpoints:
      - gov_auth
    policies:
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false
      - request-transformer:
        - action:
            body:
              add:
                token: req.user
      - proxy:
        - action:
            serviceEndpoint: govAuthService
  
  gov_no_auth:
    apiEndpoints:
      - gov_no_auth
    policies:
      - proxy:
        - action:
            serviceEndpoint: govNoAuthService

      